from typing import Protocol

from app.infra.db.orm.article import ArticleORM


class ArticleRepository(Protocol):
    def get(self, article_id: str) -> ArticleORM | None: ...
    def get_by_hash(self, content_hash: str) -> ArticleORM | None: ...
    def get_by_source_url(self, source_url: str) -> ArticleORM | None: ...
    def create(self, **kwargs) -> ArticleORM: ...
    def update(self, article_id: str, **kwargs) -> ArticleORM: ...
    def update_status(self, article_id: str, status: str) -> ArticleORM: ...
