from typing import Protocol

from app.infra.db.orm.candidate_span import CandidateSpanORM


class CandidateSpanRepository(Protocol):
    def replace_for_article(self, article_id: str, spans: list[dict]) -> list[CandidateSpanORM]: ...
    def list_by_article(self, article_id: str) -> list[CandidateSpanORM]: ...
    def list_new(self, article_id: str) -> list[CandidateSpanORM]: ...
    def mark_status(self, span_id: str, status: str) -> CandidateSpanORM: ...
    def get(self, span_id: str) -> CandidateSpanORM | None: ...
