from typing import Any, Protocol

from app.infra.db.orm.material_span import MaterialSpanORM


class MaterialSpanRepository(Protocol):
    def create(self, **kwargs) -> MaterialSpanORM: ...
    def get(self, material_id: str) -> MaterialSpanORM | None: ...
    def search(self, filters: dict[str, Any]) -> list[MaterialSpanORM]: ...
    def update_status(self, material_id: str, status: str, release_channel: str | None = None) -> MaterialSpanORM: ...
    def update_metrics(self, material_id: str, **kwargs) -> MaterialSpanORM: ...
